name: run tests for flixcal

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        #- name: Install Poetry
        #uses: snok/install-poetry@v1
      - name: install poetry
        run: sudo apt-get install -y python3-poetry-core
      - name: Lint with flake8
        run: |
          poetry run flake8 --ignore=E501 --show-source --statistics flixcal/
      - name: Type check with mypy
        run: |
          poetry run mypy flixcal/
      - name: Test with pytest
        run: |
          poetry run pytest -v -s tests/.
